name: Python task, checking prime and making unit tests

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: run_unit_tests
        run: |
          python3 test_prime.py |& tee a.txt
          cat a.txt | tail -c -3 |& tee b.txt

      
      - name: Continue to next step
        run: |
          bash check.sh
      
      